### ISSUE TITLE
Units get stuck on spawning

### ISSUE THREAD

**Issue by sanderd17** [na-Itms/0ad#11] opened 2015-05-26 08:41 UTC
It's pretty easy to reproduce when you spawn a lot of units at once on a clear map (f.e. 50 units always results in some getting stuck). But I think it's related to available spawning space, in combination with collisions, so in maps with dense obstructions, it will probably happen more often.

The easiest way to reproduce it is using some cheats to get the resources, pop cap, and speed up things, then place the rallypoint at a distance (to see units moving), and spawn a number of units.

When spawning 100 units from a CC, I get 3 stuck. When spawning 50 units, I get 2 stuck. When spawning 20 units, I get 1 stuck (note that ungarrisoning 20 units isn't too rare in-game).

When the first formation is formed, the stuck units keep playing the "walking" animation, but they stay on their position next to the building. Only when the formation changes shape (when it approaches the destination), the units get a new move command, and do start walking now. The units also move when you task them to somewhere else.

So it's probably because the first path attempt failed, and they didn't try new attempts. Note that trying new attempts may also be dangerous, as it may get into an infinite loop when a path is not possible. So there should at least be a certain timeout before a new path is searched.

**Comment by sanderd17** [comment] 2015-05-26 08:56
Hmm, the same issues also happen when attacking. The moment the formation disbands, and units search their own path to attack, they collide and get stuck in the walking animation without actually moving.

So attacking a building with 40 units is no option.

**Comment by na-Itms** [comment] 2015-05-26 20:25
I'm sorry, I forgot to push it but I noticed that yesterday, and it's something I introduced in my yesterday's cleanup. But maybe the problem is not entirely fixed, I'll let you test and see how it goes.

**Comment by sanderd17** [comment] 2015-05-27 09:45
Nope, the behaviour didn't change with the last commit. I still get the same number of units getting stuck.

**Comment by na-Itms** [comment] 2015-05-30 21:19
This commit fixes the walking-without-moving problem but some units still stop their movement in the middle of the path.

**Comment by sanderd17** [comment] 2015-06-03 15:35
It looks like they stop when there's no short path possible (i.e. they're surrounded by units). But I think that's also the case with the current pathfinder. So it would be no problem to leave this issue in.

**Comment by na-Itms** [comment] 2015-06-03 16:51
Ah, I like this kind of comments :p 
I think Kenny will have some ideas about it when it's merged.

**Closed by na-Itms** 2015-06-03 16:51 UTC
